[package]
name = "running-a-rust-web-server"
version = "0.1.0"
authors = ["Andrew Schutt <schutt.andrew@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.9"
handlebars = "2.0.2"
